name       : xorg-driver-video-fbdev
version    : 0.5.0
release    : 25
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-fbdev-0.5.0.tar.gz : a31f62db237a5c25bb087713a22a867a9b7680833ce3b644ecd712887b7b1d62
license    :
    - MIT
summary    : Framebuffer Video Driver
component  : xorg.driver
description: |
    The Xorg Fbdev Driver package contains the X.Org Video Driver for framebuffer
    devices. This driver is often used as fallback driver if the hardware
    specific and VESA drivers fail to load or are not present.
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
