name       : xorg-driver-video-fbdev
version    : 0.4.4
release    : 16
source     :
    - http://xorg.freedesktop.org/archive/individual/driver/xf86-video-fbdev-0.4.4.tar.bz2 : 9dd4b326498223abbfdf786089a46ea3db4fa6bbd341308eb48a9e00bc3fd51b
license    :
    - MIT
summary    : Framebuffer Video Driver
component  : xorg.driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   : no-bind-now
description: |
    The Xorg Fbdev Driver package contains the X.Org Video Driver for framebuffer devices. This driver is often used as fallback driver if the hardware specific and VESA drivers fail to load or are not present.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
